development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  host: localhost
  
test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  host: localhost
  